---
name: Build & Test
description: Build the final container image and run tests on it

inputs:
  registry:
    description: Target registry to push the final image.
    default: "localhost:5000"
  namespace:
    description: Namespace of the container image.
    default: ansible
  final_image:
    description: Name of the final image.
    default: community-ansible-devspaces-image

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare
      shell: bash
      run: |
        platform=${{ matrix.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # network=host driver-opt needed to push to local registry
        driver-opts: network=host

    - name: Build final image for ${{ matrix.platform }}
      id: build-final
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}/context
        provenance: false
        file: ${{ github.workspace }}/Containerfile
        load: true
        tags: |
          ${{ inputs.namespace }}/${{ inputs.final_image }}:test
        build-contexts: |
          ${{ inputs.final_image }}-base=docker-image://localhost:5000/${{ inputs.final_image }}-base:latest
        platforms: ${{ matrix.platform }}
        cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
        cache-to: type=gha,scope=build-${{ env.PLATFORM_PAIR }}

    - name: Validate if the final image is a valid EE
      shell: bash
      run: |
        python3 -m pip install --upgrade ansible-navigator
        ansible-navigator --version
        ansible-navigator run ${{ github.workspace }}/site.yml --ce docker --mode stdout --eei ${{ inputs.namespace }}/${{ inputs.final_image }}:test 

    - name: Push the built image to ${{ inputs.registry }} by digest for ${{ matrix.platform }}
      id: push-final
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}/context
        provenance: false
        file: ${{ github.workspace }}/Containerfile
        build-contexts: |
          ${{ inputs.final_image }}-base=docker-image://localhost:5000/${{ inputs.final_image }}-base:latest
        platforms: ${{ matrix.platform }}
        outputs: type=image,name=${{ inputs.registry }}/${{ inputs.namespace }}/${{ inputs.final_image }},push-by-digest=true,name-canonical=true,push=true

    - name: Export digest
      shell: bash
      run: |
        rm -rf /tmp/digests
        mkdir -p /tmp/digests
        digest="${{ steps.push-final.outputs.digest }}"
        touch "/tmp/digests/${digest#sha256:}"

    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: /tmp/digests/*
        if-no-files-found: error
        retention-days: 1

    # this step is ONLY needed for maintainence of self hosted runners
    - name: Cleanup docker
      shell: bash
      if: always()
      run: |
        docker system prune -af --volumes
